# ------------------------------------------------------------------------------------------------------
# Script to run no-etiology case-only comparison for meta-analysis - culture attributable Shigella
# ------------------------------------------------------------------------------------------------------

here::i_am("code/run_analyses/run_no_etiology_culture.R")

#library(abxGrowth)
devtools::load_all("../packages/abxGrowth")

library(SuperLearner)

source(here::here("code/run_analyses/SL.wrappers.R"))

# Load data ----------------------------------------------

# Comparison to other diarrhea
gems_data <- readRDS(here::here("data/gems_data/gems_data.Rds"))
maled_data <- readRDS(here::here("data/maled_data/maled_data.Rds"))
maled_data_MSD <- readRDS(here::here("data/maled_data/maled_data_shig_MSD_only.Rds"))
vida_data <- readRDS(here::here("data/vida_data/vida_data.Rds"))
efgh_data <- readRDS(here::here("data/efgh_data/efgh_data.Rds"))

# Outcome 1, Missingness
sl.library.with.abx <- list(c("SL.glm", "SL.screen.abx.lt.min_prop"),
                            c("SL.glm", "SL.screen.abx.glmnet"),
                            c("SL.glm.spline.age.haz", "SL.screen.abx.lt.min_prop"),
                            "SL.step.forward.spline.age.haz.abx",
                            "SL.glmnet",
                            "SL.ranger",
                            "SL.earth",
                            "SL.xgboost")

# Propensity, outcome 2
sl.library.without.abx <- list(c("SL.glm", "SL.screen.abx.lt.min_prop"),
                               c("SL.glm", "screen.glmnet"),
                               c("SL.glm.spline.age.haz", "SL.screen.abx.lt.min_prop"),
                               "SL.step.forward.spline.age.haz",
                               "SL.glmnet",
                               "SL.ranger",
                               "SL.earth",
                               "SL.xgboost")

# GEMS ANALYSIS --------------------------------------------

# Impute missing covariates
gems_data_imp <- impute_covariates(gems_data,
                                   imp_covariates = c("sex",
                                                      "age",
                                                      "ses_quintile",
                                                      "safe_water",
                                                      "safe_sanit",
                                                      "enr_haz",
                                                      "prim_caregiver_edu_bin",
                                                      "num_hh_lt5",
                                                      "rotavirus_attributable",
                                                      "adenovirus_attributable",
                                                      "aeromonas_attributable",
                                                      "astro_attributable",
                                                      "cryptosporidium_attributable",
                                                      "cyclospora_attributable",
                                                      "e_histolytica_attributable",
                                                      "isospora_attributable",
                                                      "noro_attributable",
                                                      "salmonella_attributable",
                                                      "sapovirus_attributable",
                                                      "st_etec_attributable",
                                                      "tepec_attributable",
                                                      "v_cholerae_attributable",
                                                      "EAEC_attributable",
                                                      "shigella_new",
                                                      "rotavirus_new",
                                                      "adenovirus_new",
                                                      "st_etec_new",
                                                      "lt_etec_new",
                                                      "crypto_new",
                                                      "astro_new" ,
                                                      "noro_new",
                                                      "tepec_new" ,
                                                      "campy_new",
                                                      "sapo_new",
                                                      "e_bieneusi_new",
                                                      "giardia_new",
                                                      "EAEC_new", 
                                                      "dysentery",
                                                      "vomit",
                                                      "fever",
                                                      "lsstools",
                                                      "who_dehyd",
                                                      "duration_pre_enroll"))

one_hot_gems <- one_hot_encode(gems_data_imp,
                               laz_var_name = "hazd60",
                               covariate_list = c("sex",
                                                  "age",
                                                  "ses_quintile",
                                                  "safe_water",
                                                  "safe_sanit",
                                                  "enr_haz",
                                                  "prim_caregiver_edu_bin",
                                                  "num_hh_lt5",
                                                  "I_followup_days",
                                                  "I_followup_days_x_followup_days",
                                                  "site"),
                               abx_var_name = "all_abx",
                               site_var_name = "site",
                               site_interaction = TRUE,
                               severity_list = c("dysentery",
                                                 "vomit",
                                                 "fever",
                                                 "lsstools",
                                                 "who_dehyd",
                                                 "duration_pre_enroll"),
                               age_var_name = "age")

gems_results <- agaipw(data = one_hot_gems$data,
                       laz_var_name = "hazd60",
                       abx_var_name = "all_abx", 
                       infection_var_name = "shigella_attributable_culture",
                       followup_var_names = c("I_followup_days", "I_followup_days_x_followup_days"),
                       site_var_name = one_hot_gems$site_var_names,
                       covariate_list = one_hot_gems$covariate_list,
                       pathogen_quantity_list = c("shigella_new",
                                                  "rotavirus_new",
                                                  "adenovirus_new",
                                                  "st_etec_new",
                                                  "lt_etec_new",
                                                  "crypto_new",
                                                  "astro_new" ,
                                                  "noro_new",
                                                  "tepec_new" ,
                                                  "campy_new",
                                                  "sapo_new",
                                                  "e_bieneusi_new",
                                                  "giardia_new",
                                                  "EAEC_new"),
                       severity_list = one_hot_gems$severity_list,
                       no_etiology_var_name = "no_etiology",
                       first_id_var_name = "first_id",
                       outcome_type = "gaussian",
                       sl.library.outcome = sl.library.with.abx,
                       sl.library.outcome.2 = sl.library.without.abx,
                       sl.library.treatment = sl.library.without.abx,
                       sl.library.infection = sl.library.without.abx,
                       sl.library.missingness = sl.library.with.abx,
                       v_folds = 5, 
                       return_models = TRUE,
                       msm = TRUE,
                       msm_var_name = "age",
                       msm_formula = "age")

saveRDS(gems_results, here::here("results/no_etiology/gems_results_culture.Rds"))
gems_results$aipw_est$aipw_models <- NULL
saveRDS(gems_results, here::here("results/no_etiology/gems_results_culture_no_models.Rds"))

# MAL-ED ANALYSIS ----------------------------------------------------------------------

maled_data_imp <- impute_covariates(data = maled_data,
                                    site_var_name = "site",
                                    imp_by_site = TRUE,
                                    imp_covariates = c("site",
                                                       "sex",
                                                       "agemonths",
                                                       "baseline_haz",
                                                       "wami_quintile",
                                                       "mated_bin", 
                                                       "drinkimp",
                                                       "sanitimp",
                                                       "adenovirus_40_41_new", 
                                                       "shigella_new",
                                                       "aeromonas_new",                         
                                                       "astrovirus_new",                        
                                                       "campylobacter_pan_new",                 
                                                       "cryptosporidium_new",                   
                                                       "cyclospora_new",                        
                                                       "e_histolytica_new",                     
                                                       "isospora_new",                          
                                                       "norovirus_new",                         
                                                       "rotavirus_new",                         
                                                       "salmonella_new",                        
                                                       "sapovirus_new",                         
                                                       "st_etec_new",                           
                                                       "tEPEC_new",                             
                                                       "v_cholerae_new",                        
                                                       "ETEC_new",                              
                                                       "e_bieneusi_new",                        
                                                       "eaec_new",
                                                       "dysentery",
                                                       "fever",
                                                       "fever_days",
                                                       "dehyd",
                                                       "lsstools",
                                                       "daysvomit"))

# Add "age" and "enr_haz" to match wrappers (go back and rename in raw data later)
maled_data_imp$age <- maled_data_imp$agemonths
maled_data_imp$enr_haz <- maled_data_imp$baseline_haz

# Drop people with NA Shigella culture results
maled_data_imp <- maled_data_imp[which(!is.na(maled_data_imp$culture_shigella)),]

one_hot_maled <- one_hot_encode(data = maled_data_imp,
                                laz_var_name = "month3_haz",
                                covariate_list = c("site",
                                                   "sex",
                                                   "age",
                                                   "wami_quintile",
                                                   "enr_haz",
                                                   "mated_bin", 
                                                   "drinkimp",
                                                   "sanitimp",
                                                   "I_followup_days",
                                                   "I_followup_days_x_followup_days"),
                                abx_var_name = "all_abx",
                                site_var_name = "site",
                                site_interaction = TRUE,
                                severity_list = c("dysentery",
                                                  "fever",
                                                  "fever_days",
                                                  "dehyd",
                                                  "lsstools",
                                                  "daysvomit",
                                                  "duration_pre_abx"),
                                age_var_name = "age")

maled_results <- agaipw(data = one_hot_maled$data,
                        laz_var_name = "month3_haz",
                        abx_var_name = "all_abx", 
                        infection_var_name = "culture_shigella",
                        site_var_name = one_hot_maled$site_var_names,
                        followup_var_names = c("I_followup_days", "I_followup_days_x_followup_days"),
                        covariate_list = one_hot_maled$covariate_list,
                        pathogen_quantity_list = c("shigella_new",            
                                                   "adenovirus_40_41_new",                  
                                                   "aeromonas_new",                         
                                                   "astrovirus_new",                        
                                                   "campylobacter_pan_new",                 
                                                   "cryptosporidium_new",                   
                                                   "cyclospora_new",                        
                                                   "e_histolytica_new",                     
                                                   "isospora_new",                          
                                                   "norovirus_new",                         
                                                   "rotavirus_new",                         
                                                   "salmonella_new",                        
                                                   "sapovirus_new",                         
                                                   "st_etec_new",                           
                                                   "tEPEC_new",                             
                                                   "v_cholerae_new",                        
                                                   "ETEC_new",                              
                                                   "e_bieneusi_new",                        
                                                   "eaec_new"),
                        severity_list = one_hot_maled$severity_list,
                        no_etiology_var_name = "no_etiology",
                        outcome_type = "gaussian",
                        sl.library.outcome = sl.library.with.abx,
                        sl.library.outcome.2 = sl.library.without.abx,
                        sl.library.treatment = sl.library.without.abx,
                        sl.library.infection = sl.library.without.abx,
                        sl.library.missingness = c("SL.mean"), # switch to mean bc only one missing obs, breaking with full lib # sl.library.with.abx,
                        v_folds = 5, 
                        return_models = TRUE,
                        msm = TRUE,
                        msm_var_name = "age",
                        msm_formula = "age",
                        first_id_var_name = "pid")

saveRDS(maled_results, here::here("results/no_etiology/maled_results_culture.Rds"))
maled_results$aipw_est$aipw_models <- NULL
saveRDS(maled_results, here::here("results/no_etiology/maled_results_culture_no_models.Rds"))

# MSD only
maled_data_imp_MSD <- impute_covariates(data = maled_data_MSD,
                                        site_var_name = "site",
                                        imp_by_site = TRUE,
                                        imp_covariates = c("site",
                                                           "sex",
                                                           "agemonths",
                                                           "baseline_haz",
                                                           "wami_quintile",
                                                           "mated_bin", 
                                                           "drinkimp",
                                                           "sanitimp",
                                                           "adenovirus_40_41_new", 
                                                           "shigella_new",
                                                           "aeromonas_new",                         
                                                           "astrovirus_new",                        
                                                           "campylobacter_pan_new",                 
                                                           "cryptosporidium_new",                   
                                                           "cyclospora_new",                        
                                                           "e_histolytica_new",                     
                                                           "isospora_new",                          
                                                           "norovirus_new",                         
                                                           "rotavirus_new",                         
                                                           "salmonella_new",                        
                                                           "sapovirus_new",                         
                                                           "st_etec_new",                           
                                                           "tEPEC_new",                             
                                                           "v_cholerae_new",                        
                                                           "ETEC_new",                              
                                                           "e_bieneusi_new",                        
                                                           "eaec_new",
                                                           "dysentery",
                                                           "fever",
                                                           "fever_days",
                                                           "dehyd",
                                                           "lsstools",
                                                           "daysvomit"))

# Add "age" and "enr_haz" to match wrappers (go back and rename in raw data later)
maled_data_imp_MSD$age <- maled_data_imp_MSD$agemonths
maled_data_imp_MSD$enr_haz <- maled_data_imp_MSD$baseline_haz

# Drop people with NA Shigella culture results
maled_data_imp_MSD <- maled_data_imp_MSD[which(!is.na(maled_data_imp_MSD$culture_shigella)),]

one_hot_maled_MSD <- one_hot_encode(data = maled_data_imp_MSD,
                                    laz_var_name = "month3_haz",
                                    covariate_list = c("site",
                                                       "sex",
                                                       "age",
                                                       "wami_quintile",
                                                       "enr_haz",
                                                       "mated_bin", 
                                                       "drinkimp",
                                                       "sanitimp",
                                                       "I_followup_days",
                                                       "I_followup_days_x_followup_days"),
                                    abx_var_name = "all_abx",
                                    site_var_name = "site",
                                    site_interaction = TRUE,
                                    severity_list = c("dysentery",
                                                      "fever",
                                                      "fever_days",
                                                      "dehyd",
                                                      "lsstools",
                                                      "daysvomit",
                                                      "duration_pre_abx"),
                                    age_var_name = "age")

maled_results_MSD <- agaipw(data = one_hot_maled_MSD$data,
                            laz_var_name = "month3_haz",
                            abx_var_name = "all_abx", 
                            infection_var_name = "culture_shigella",
                            site_var_name = one_hot_maled$site_var_names,
                            followup_var_names = c("I_followup_days", "I_followup_days_x_followup_days"),
                            covariate_list = one_hot_maled$covariate_list,
                            pathogen_quantity_list = c("shigella_new",            
                                                       "adenovirus_40_41_new",                  
                                                       "aeromonas_new",                         
                                                       "astrovirus_new",                        
                                                       "campylobacter_pan_new",                 
                                                       "cryptosporidium_new",                   
                                                       "cyclospora_new",                        
                                                       "e_histolytica_new",                     
                                                       "isospora_new",                          
                                                       "norovirus_new",                         
                                                       "rotavirus_new",                         
                                                       "salmonella_new",                        
                                                       "sapovirus_new",                         
                                                       "st_etec_new",                           
                                                       "tEPEC_new",                             
                                                       "v_cholerae_new",                        
                                                       "ETEC_new",                              
                                                       "e_bieneusi_new",                        
                                                       "eaec_new"),
                            severity_list = one_hot_maled$severity_list,
                            no_etiology_var_name = "no_etiology",
                            outcome_type = "gaussian",
                            sl.library.outcome = sl.library.with.abx,
                            sl.library.outcome.2 = sl.library.without.abx,
                            sl.library.treatment = sl.library.without.abx,
                            sl.library.infection = sl.library.without.abx,
                            sl.library.missingness = c("SL.mean"), #  mean in MSD only version bc only one missing obs
                            v_folds = 5, 
                            return_models = TRUE,
                            msm = TRUE,
                            msm_var_name = "age",
                            msm_formula = "age",
                            first_id_var_name = "pid")

saveRDS(maled_results, here::here("results/no_etiology/maled_results_MSD_culture.Rds"))
maled_results$aipw_est$aipw_models <- NULL
saveRDS(maled_results, here::here("results/no_etiology/maled_results_MSD_culture_no_models.Rds"))


# VIDA ANALYSIS ----------------------------------------------------------------------

vida_data_imp <- impute_covariates(data = vida_data,
                                   site_var_name = "site",
                                   imp_by_site = TRUE,
                                   imp_covariates = c("sex",
                                                      "agemchild",
                                                      "ses_quintile",
                                                      "safe_water",
                                                      "safe_sanit",
                                                      "enr_haz",
                                                      "site",
                                                      "education_bin",
                                                      "num_hh_lt5",
                                                      "I_followup_days",
                                                      "I_followup_days_x_followup_days",
                                                      "shigella_new",                   
                                                      "rotavirus_new",                  
                                                      "st_etec_new",                    
                                                      "crypto_new",                     
                                                      "adeno_new",                      
                                                      "astro_new",                      
                                                      "noro_gii_new",                       
                                                      "tepec_new",                      
                                                      "campy_new",                      
                                                      "sapo_new",                       
                                                      "giardia_new",                    
                                                      "eaec_new",
                                                      "lsstools",
                                                      "vom_days",
                                                      "vom_freq",
                                                      "fever",
                                                      "dehydr",
                                                      "dysentery",
                                                      "duration_pre_enroll"))

vida_data_imp$age <- vida_data_imp$agemchild
vida_data_imp <- vida_data_imp[which(!is.na(vida_data_imp$tac_shig)),]

one_hot_vida <- one_hot_encode(data = vida_data_imp,
                               laz_var_name = "hazd60",
                               covariate_list = c("sex",
                                                  "age",
                                                  "ses_quintile",
                                                  "safe_water",
                                                  "safe_sanit",
                                                  "enr_haz",
                                                  "site",
                                                  "education_bin",
                                                  "num_hh_lt5",
                                                  "I_followup_days",
                                                  "I_followup_days_x_followup_days"),
                               abx_var_name = "all_abx",
                               site_var_name = "site",
                               site_interaction = TRUE,
                               severity_list = c("lsstools",
                                                 "vom_days",
                                                 "vom_freq",
                                                 "fever",
                                                 "dehydr",
                                                 "dysentery",
                                                 "duration_pre_enroll"),
                               age_var_name = "age")

vida_results <- agaipw(data = one_hot_vida$data,
                       laz_var_name = "hazd60",
                       abx_var_name = "all_abx", 
                       infection_var_name = "shigella_culture_positive",
                       followup_var_names = c("I_followup_days", "I_followup_days_x_followup_days"),
                       site_var_name = one_hot_vida$site_var_names,
                       covariate_list = one_hot_vida$covariate_list,
                       pathogen_quantity_list = c("shigella_new",                   
                                                  "rotavirus_new",                  
                                                  "st_etec_new",                    
                                                  "crypto_new",                     
                                                  "adeno_new",                      
                                                  "astro_new",                      
                                                  "noro_gii_new",                       
                                                  "tepec_new",                      
                                                  "campy_new",                      
                                                  "sapo_new",                       
                                                  "giardia_new",                    
                                                  "eaec_new"),
                       no_etiology_var_name = "no_etiology",
                       first_id_var_name = "first_id",
                       severity_list = one_hot_vida$severity_list,
                       outcome_type = "gaussian",
                       sl.library.outcome = sl.library.with.abx,
                       sl.library.outcome.2 = sl.library.without.abx,
                       sl.library.treatment = sl.library.without.abx,
                       sl.library.infection = sl.library.without.abx,
                       sl.library.missingness = sl.library.with.abx,
                       v_folds = 5, 
                       return_models = TRUE,
                       msm = TRUE,
                       msm_var_name = "age",
                       msm_formula = "age")

saveRDS(vida_results, here::here("results/no_etiology/vida_results_culture.Rds"))
vida_results$aipw_est$aipw_models <- NULL
saveRDS(vida_results, here::here("results/no_etiology/vida_results_culture_no_models.Rds"))

# EFGH ANALYSIS ------------------------------------------------------------------------

efgh_data_imp <- impute_covariates(data = efgh_data,
                                   site_var_name = "enroll_site",
                                   imp_covariates = c("sex",
                                                      "enr_age_months",
                                                      "enr_haz",
                                                      "final_quintile_site",
                                                      "imp_water",
                                                      "imp_toi",
                                                      "enroll_ai_num_child",
                                                      "moth_ed_bin",
                                                      "I_mo3_days",
                                                      "I_mo3_days_x_mo3_days",
                                                      "enroll_diar_blood",
                                                      "enroll_diar_vom_days",
                                                      "enroll_diar_vom_num",
                                                      "enroll_diar_fever_days",
                                                      "enroll_diar_fever",
                                                      "enroll_diar_loose_num",
                                                      "enroll_cond_dehyd",
                                                      "duration_pre_enroll",
                                                      "shigella_new",               
                                                      "rotavirus_new",              
                                                      "adenovirus_new",             
                                                      "ETEC_new",                   
                                                      "cryptosporidium_new",        
                                                      "astrovirus_new",             
                                                      "norovirus_gii_new",              
                                                      "c_jejuni_new",               
                                                      "tEPEC_new",                  
                                                      "sapovirus_new",              
                                                      "e_bieneusi_new",             
                                                      "giardia_new",                
                                                      "EAEC_new"))

efgh_data_imp$age <- efgh_data_imp$enr_age_months
efgh_data_imp <- efgh_data_imp[which(!is.na(efgh_data_imp$tac_shigella_attributable)),]

one_hot_efgh <- one_hot_encode(data = efgh_data_imp,
                               laz_var_name = "mo3_haz",
                               covariate_list = c("sex",
                                                  "age",
                                                  "enr_haz",
                                                  "final_quintile_site",
                                                  "imp_water",
                                                  "imp_toi",
                                                  "enroll_ai_num_child",
                                                  "moth_ed_bin",
                                                  "I_mo3_days",
                                                  "I_mo3_days_x_mo3_days"),
                               abx_var_name = "all_abx",
                               site_var_name = "enroll_site",
                               site_interaction = TRUE,
                               severity_list = c("enroll_diar_blood",
                                                 "enroll_diar_vom_days",
                                                 "enroll_diar_vom_num",
                                                 "enroll_diar_fever_days",
                                                 "enroll_diar_fever",
                                                 "enroll_diar_loose_num",
                                                 "enroll_cond_dehyd",
                                                 "duration_pre_enroll"),
                               age_var_name = "age")

efgh_results <- agaipw(data = one_hot_efgh$data,
                       laz_var_name = "mo3_haz",
                       abx_var_name = "all_abx", 
                       infection_var_name = "culture_shigella_positive",
                       site_var_name = one_hot_efgh$site_var_names,
                       followup_var_names = c("I_mo3_days",
                                              "I_mo3_days_x_mo3_days"),
                       covariate_list = one_hot_efgh$covariate_list,
                       pathogen_quantity_list = c("shigella_new",               
                                                  "rotavirus_new",              
                                                  "adenovirus_new",             
                                                  "ETEC_new",                   
                                                  "cryptosporidium_new",        
                                                  "astrovirus_new",             
                                                  "norovirus_gii_new",              
                                                  "c_jejuni_new",               
                                                  "tEPEC_new",                  
                                                  "sapovirus_new",              
                                                  "e_bieneusi_new",             
                                                  "giardia_new",                
                                                  "EAEC_new"),
                       severity_list = one_hot_efgh$severity_list,
                       no_etiology_var_name = "no_etiology",
                       first_id_var_name = "first_id",
                       outcome_type = "gaussian",
                       sl.library.outcome = sl.library.with.abx,
                       sl.library.outcome.2 = sl.library.without.abx,
                       sl.library.treatment = sl.library.without.abx,
                       sl.library.infection = sl.library.without.abx,
                       sl.library.missingness = sl.library.with.abx,
                       v_folds = 5, 
                       return_models = TRUE,
                       msm = TRUE,
                       msm_var_name = "age",
                       msm_formula = "age")

saveRDS(efgh_results, here::here("results/no_etiology/efgh_results_culture.Rds"))
efgh_results$aipw_est$aipw_models <- NULL
saveRDS(efgh_results, here::here("results/no_etiology/efgh_results_culture_no_models.Rds"))

# IPD ANALYSIS ----------------------------------------------------------------

# Main dataset excludes LSD
data <- readRDS(here::here("data/ipd_data/ipd_data_no_etiology.Rds"))

imp_data <- impute_covariates(data = data,
                              imp_covariates = c("sex",
                                                 "age",
                                                 "ses_quintile",
                                                 "enr_haz",
                                                 "edu_bin",
                                                 "site",
                                                 "I_followup_days",
                                                 "I_followup_days_x_followup_days",
                                                 "dysentery",
                                                 "any_vom",
                                                 "any_fev",
                                                 "dehyd_level",
                                                 "lsstools",
                                                 "duration_pre_enroll",
                                                 "shigella_new" ,
                                                 "rotavirus_new",
                                                 "adenovirus_new" ,
                                                 "etec_new" ,
                                                 "cryptosporidium_new"  ,
                                                 "astrovirus_new" ,
                                                 "norovirus_gii_new" ,
                                                 "tepec_new",
                                                 "campylobacter_new" ,
                                                 "sapovirus_new" ,
                                                 "giardia_new"  ,
                                                 "e_bieneusi_new"  ,
                                                 "eaec_new"))

# remove missing culture shig results (a few from MAL-ED, all of ABCD)
imp_data <- imp_data[-which(is.na(imp_data$culture_shig_attr)),]

one_hot_data <- one_hot_encode(imp_data,
                               laz_var_name = "final_haz",
                               covariate_list = c("sex",
                                                  "age",
                                                  "ses_quintile",
                                                  "enr_haz",
                                                  "I_followup_days",
                                                  "I_followup_days_x_followup_days",
                                                  "site",
                                                  "edu_bin",
                                                  "num_hh_lt5",
                                                  "imp_water",
                                                  "imp_sanit"),
                               abx_var_name = "all_abx",
                               site_var_name = "site",
                               site_interaction = TRUE,
                               severity_list = c("dysentery",
                                                 "any_vom",
                                                 "lsstools",
                                                 "dehyd_level",
                                                 "duration_pre_enroll",
                                                 "any_fev"),
                               age_var_name = "age")

# The following variables are missing in some studies
# water / sanitation - missing abcd - set to 0
# num children in hh - missing maled - set to 1

ipd_results <- agaipw(data = one_hot_data$data,
                      laz_var_name = "final_haz",
                      abx_var_name = "all_abx", 
                      infection_var_name = "culture_shig_attr",
                      followup_var_names = c("I_followup_days", "I_followup_days_x_followup_days"),
                      site_var_name = one_hot_data$site_var_names,
                      covariate_list = one_hot_data$covariate_list,
                      pathogen_quantity_list = c("shigella_new",
                                                 "rotavirus_new",
                                                 "adenovirus_new",
                                                 "etec_new",
                                                 "cryptosporidium_new",
                                                 "astrovirus_new" ,
                                                 "norovirus_gii_new",
                                                 "tepec_new" ,
                                                 "campylobacter_new",
                                                 "sapovirus_new",
                                                 "e_bieneusi_new",
                                                 "giardia_new",
                                                 "eaec_new"),
                      severity_list = one_hot_data$severity_list,
                      no_etiology_var_name = "no_etiology",
                      first_id_var_name = "first_id",
                      outcome_type = "gaussian",
                      sl.library.outcome = sl.library.with.abx,
                      sl.library.outcome.2 = sl.library.without.abx,
                      sl.library.treatment = sl.library.without.abx,
                      sl.library.infection = sl.library.without.abx,
                      sl.library.missingness = sl.library.with.abx,
                      v_folds = 5, 
                      return_models = TRUE,
                      msm = TRUE,
                      msm_var_name = "age",
                      msm_formula = "age")

saveRDS(ipd_results, here::here("results/no_etiology/ipd_no_etiology_culture.Rds"))
ipd_results$aipw_est$aipw_models <- NULL
saveRDS(ipd_results, here::here("results/no_etiology/ipd_no_etiology_culture_no_models.Rds"))

# Supplement analysis including LSD
data_LSD <- readRDS(here::here("data/ipd_data/ipd_data_no_etiology_inc_LSD.Rds"))

imp_data_LSD <- impute_covariates(data = data_LSD,
                              imp_covariates = c("sex",
                                                 "age",
                                                 "ses_quintile",
                                                 "enr_haz",
                                                 "edu_bin",
                                                 "site",
                                                 "I_followup_days",
                                                 "I_followup_days_x_followup_days",
                                                 "dysentery",
                                                 "any_vom",
                                                 "any_fev",
                                                 "dehyd_level",
                                                 "lsstools",
                                                 "duration_pre_enroll",
                                                 "shigella_new" ,
                                                 "rotavirus_new",
                                                 "adenovirus_new" ,
                                                 "etec_new" ,
                                                 "cryptosporidium_new"  ,
                                                 "astrovirus_new" ,
                                                 "norovirus_gii_new" ,
                                                 "tepec_new",
                                                 "campylobacter_new" ,
                                                 "sapovirus_new" ,
                                                 "giardia_new"  ,
                                                 "e_bieneusi_new"  ,
                                                 "eaec_new"))

# remove missing culture shig results (a few from MAL-ED, all of ABCD)
imp_data_LSD <- imp_data_LSD[-which(is.na(imp_data_LSD$culture_shig_attr)),]

one_hot_data_LSD <- one_hot_encode(imp_data_LSD,
                               laz_var_name = "final_haz",
                               covariate_list = c("sex",
                                                  "age",
                                                  "ses_quintile",
                                                  "enr_haz",
                                                  "I_followup_days",
                                                  "I_followup_days_x_followup_days",
                                                  "site",
                                                  "edu_bin",
                                                  "num_hh_lt5",
                                                  "imp_water",
                                                  "imp_sanit"),
                               abx_var_name = "all_abx",
                               site_var_name = "site",
                               site_interaction = TRUE,
                               severity_list = c("dysentery",
                                                 "any_vom",
                                                 "lsstools",
                                                 "dehyd_level",
                                                 "duration_pre_enroll",
                                                 "any_fev"),
                               age_var_name = "age")

# The following variables are missing in some studies
# water / sanitation - missing abcd - set to 0
# num children in hh - missing maled - set to 1

ipd_results_LSD <- agaipw(data = one_hot_data_LSD$data,
                      laz_var_name = "final_haz",
                      abx_var_name = "all_abx", 
                      infection_var_name = "culture_shig_attr",
                      followup_var_names = c("I_followup_days", "I_followup_days_x_followup_days"),
                      site_var_name = one_hot_data_LSD$site_var_names,
                      covariate_list = one_hot_data_LSD$covariate_list,
                      pathogen_quantity_list = c("shigella_new",
                                                 "rotavirus_new",
                                                 "adenovirus_new",
                                                 "etec_new",
                                                 "cryptosporidium_new",
                                                 "astrovirus_new" ,
                                                 "norovirus_gii_new",
                                                 "tepec_new" ,
                                                 "campylobacter_new",
                                                 "sapovirus_new",
                                                 "e_bieneusi_new",
                                                 "giardia_new",
                                                 "eaec_new"),
                      severity_list = one_hot_data_LSD$severity_list,
                      no_etiology_var_name = "no_etiology",
                      first_id_var_name = "first_id",
                      outcome_type = "gaussian",
                      sl.library.outcome = sl.library.with.abx,
                      sl.library.outcome.2 = sl.library.without.abx,
                      sl.library.treatment = sl.library.without.abx,
                      sl.library.infection = sl.library.without.abx,
                      sl.library.missingness = sl.library.with.abx,
                      v_folds = 5, 
                      return_models = TRUE,
                      msm = TRUE,
                      msm_var_name = "age",
                      msm_formula = "age")

saveRDS(ipd_results_LSD, here::here("results/no_etiology/ipd_no_etiology_culture_LSD.Rds"))
ipd_results_LSD$aipw_est$aipw_models <- NULL
saveRDS(ipd_results_LSD, here::here("results/no_etiology/ipd_no_etiology_culture_LSD_no_models.Rds"))

